/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vendor_xiaomi_hardware_miperf_V1_0_MiPerf */

#ifndef _Included_vendor_xiaomi_hardware_miperf_V1_0_MiPerf
#define _Included_vendor_xiaomi_hardware_miperf_V1_0_MiPerf


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_os_MiPerf
 * Method:    nativePerfAcqXml
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_android_os_MiPerf_nativePerfAcqXml(JNIEnv *env, jclass, jint pid, jstring activityName, jstring packageName, jstring boostMode);

/*
 * Class:     android_os_MiPerf
 * Method:    nativeGetXmlHashMap
 * Signature: ()I
 */
JNIEXPORT jobject JNICALL Java_android_os_MiPerf_nativeGetXmlHashMap(JNIEnv *env, jclass);
/*
 * Class:     android_os_MiPerf
 * Method:    nativeGetXmlHashMap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_android_os_MiPerf_nativeUpdateConfig(JNIEnv *env, jclass);

#ifdef __cplusplus
}
#endif
#endif
