/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_miui_misight_MiSight */

#ifndef _Included_com_miui_misight_MiSight
#define _Included_com_miui_misight_MiSight
#ifdef __cplusplus
extern "C" {
#endif


#include <binder/IServiceManager.h>
#include <android_runtime/AndroidRuntime.h>


/*
 * Class:     com_miui_misight_MiSight
 * Method:    nativeSendEvent
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_miui_misight_MiSight_nativeSendEvent
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif