/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_module3_Module3JNI */

#ifndef _Included_com_demo_module3_Module3JNI
#define _Included_com_demo_module3_Module3JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_module3_Module3JNI
 * Method:    getMessage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_demo_module3_Module3JNI_getMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
