/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaomi_entitlement_utils_EapAka */

#ifndef _Included_com_xiaomi_entitlement_utils_EapAka
#define _Included_com_xiaomi_entitlement_utils_EapAka

/*
 * Class:     com_xiaomi_entitlement_utils_EapAka
 * Method:    getEapAkaAuthKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xiaomi_entitlement_utils_EapAka_getEapAkaAuthKey
      (JNIEnv *, jclass, jstring);

#endif
